site_name: Serveis de Xarxa i Internet
site_url: https://fbarraga.github.io/serveisxarxa

nav:
  - Inici: index.md
  - Programació: programacio.md
  - DHCP: DHCP/dhcp.md
  - DNS: DNS/dns.md
  - Serveis Web: serveiweb/serveisweb.md
  - Serveis FTP: serveiftp/serveisftp.md
  - EMail: email/email.md
  - Missatgeria: missatgeria/missatgeria.md
  - Audio: audio/audio.md
  - Video: video/video.md
  - Recursos: recursos.md
  - Contacte: contacte.md

theme:
  name: material
  features:
    #- toc.integrate  # (si quieres que esté integrada en el menú lateral izquierdo en vez de la derecha)
    - navigation.footer
    - content.code.copy # para que puedan copiar el contenido
  font:
    text: Roboto
    code: Roboto Mono
  
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  
     
  language: ca

markdown_extensions:
  - pymdownx.superfences: # per utilitzar superfences pero hi ha opcions de pago.De moment mermaid amb javascript
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@francescbarragan
    - icon: simple/github
      link: https://githum.com/francescbarragan    
    - icon: simple/x
      link: https://x.com/francescbarragan
    - icon: simple/mailboxdotorg
      link: fbarragan@sapalomera.cat

extra_css:
  - styles/extra.css # ampliar pantalla

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js   # CDN de mermaid
  - js/mermaid_init.js                                # fitxer local d'inicialització

plugins:
  - search
